version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db_odoo18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo18-custom:latest
    container_name: web_odoo18
    depends_on:
      db:
        condition: service_healthy
    # No publicar puertos. EasyPanel hará el proxy/SSL.
    expose:
      - "8069"   # HTTP Odoo
      - "8072"   # longpolling/bus
    volumes:
      - ./odoo_conf/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/addons
      - ./extra-addons:/mnt/extra-addons
      - odoo-filestore:/var/lib/odoo
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:8069/web/login', timeout=5); sys.exit(0)\""]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-filestore:
